### PR TITLE
Added example for building a dynamic query to documentation.

### PR DESCRIPTION
**Pull request by albertreed**
See: https://github.com/gajus/slonik/issues/300

### CODE REVIEW

**Comment by albertreed** [comment]
@gajus Any thoughts here? Was going to take a small handful of documentation items from past questions but wanted to be sure I'm on the right track before going wider.

**Comment by gajus** [comment]
Frankly, I found this addition confusing.

If it was me, I would have written something along the lines of:

### Building dynamic queries

Queries are built using `sql` tag and those tags can be nested to create dynamic queries, e.g.

```ts
const whereFragment = sql`WHERE bar='baz'`;
const fooQuery = sql`SELECT * FROM foo ${whereFragment}`;
```

In the above example `whereFragment` is embedded in `fooQuery`. Therefore, the resulting query is equivalent to:

```sql
SELECT *
FROM foo
WHERE bar='baz'
```

**Comment by AndrewJo** [comment]
In addition, I find that `sql.join` is better suited for more complex dynamic queries and scales better if you have more than just a couple of clauses in addition to other query building blocks provided by Slonik.

Expanding the proposal a bit to add additional clauses:

```js
const field1 = 1;
const field2Clause = someValue ? sql` and field2=${someValue}` : sql``;
const field3Clause = otherValue ? sql` and field3=${otherValue}` : sql``;
const finalQuery = sql`SELECT * FROM table WHERE field1=${field1}${field2Clause}${field3Clause}`;
```

If you have more than a couple of fields, `sql.join` especially makes the code cleaner compared to tacking on `${}` one after another:

```js
const whereClauses = [sql`field1 = ${field1}`];
if (someValue) whereClauses.push(sql`field2 = ${someValue}`);
if (otherValue) whereClauses.push(sql`field3 = ${otherValue}`);
const finalQuery = sql`SELECT * FROM "table" WHERE ${sql.join(whereClauses, sql` AND `)}`;
```

See this convoluted example from what I use at my company for generating dynamic JOIN statements:

```js
/**
 * Gets the building for an electrical panel, a circuit breaker, or at a lower level, a device
 * Building has many electrical panels, panels have many circuit breakers.
 */
async function getBuilding(connection, entity, entityId) {
  const joinClauses = [];

  // Switch fallthrough is very useful for constructing joins
  switch (entity) {
    case "devices":
      joinClauses.unshift(sql`INNER JOIN devices ON devices.circuit_breaker_id = circuit_breakers.id`);
    case "circuit_breakers":
      joinClauses.unshift(sql`INNER JOIN circuit_breakers ON circuit_breakers.panel_id = panels.id`);
    case "panels":
      joinClauses.unshift(sql`INNER JOIN panels ON panels.building_id = buildings.id`);
    break;
  }

  return connection.one(sql`
    SELECT * FROM buildings 
    ${sql.join(joinClauses, sql`\n`)
    WHERE ${sql.identifier([entity, "id"]) = ${entityId}`);
}
```

The above function dynamically generates queries based on the input:
```js
getBuilding(connection, "device", 1);

/* Generated query:
SELECT * FROM buildings
INNER JOIN panels ON panels.building_id = buildings.id
INNER JOIN circuit_breakers ON circuit_breakers.panel_id = panels.id
INNER JOIN devices ON devices.circuit_breaker_id = circuit_breakers.id
WHERE "devices"."id" = 1
*/

getBuilding(connection, "panels", 8);

/* Generated query:
SELECT * FROM buildings
INNER JOIN panels ON panels.building_id = buildings.id
WHERE "panels"."id" = 8
*/
```

**Comment by albertreed** [comment]
Hey all - Just wanted to see that I hadn't forgotten this. Digging out of some work stuff but will still get to it (and some other doc requests).

**Comment by bootrino** [comment]
I've spent nearly an hour trying to find out the right way to do this.

It would be enormously helpful and time saving if this bit of documentation was on the README/front page/ right up the front of the documentation.  This is precisely the information I needed

https://github.com/gajus/slonik/pull/305#issuecomment-968994299

Even better if it continued on to provide this information:

https://github.com/gajus/slonik/pull/305#issuecomment-973324847

This thread should be the star paragraph of the documentation, not stuck in an issue thread.

**Comment by gajus** [comment]
@bootrino Please consider contributing documentation improvements.

For those who have been using this library for 5 years+ everything becomes obvious, so it is really hard to think through the eyes of a first time user.

**Comment by gajus** [comment]
Wrote an article walking through query building using Slonik.

https://contra.com/p/AqZWWoUB-writing-composable-sql-using-java-script

**Pull request closed without merging**
